# # -*- coding: utf-8 -*-
# """model_densenet.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1HH4oqk2q3xkXM9vvXGezLXZOAeUIXSmF

# Upload Dataset in Google Colab
# """

# from google.colab import files
# uploaded = files.upload()

# """Extract Dataset"""

# import zipfile

# with zipfile.ZipFile("liver_dataset.zip", 'r') as zip_ref:
#     zip_ref.extractall("/content/liver_dataset")

# """Check"""

# import os
# os.listdir("/content/liver_dataset")

# """Import Required Libraries"""

# import tensorflow as tf
# from tensorflow.keras.preprocessing.image import ImageDataGenerator
# from tensorflow.keras.applications import DenseNet121
# from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
# from tensorflow.keras.models import Model
# from tensorflow.keras.optimizers import Adam

# """Train / Validation / Test Split"""

# IMG_SIZE = 224
# BATCH_SIZE = 16
# DATASET_PATH = "/content/liver_dataset"

# """Data generators:"""

# datagen = ImageDataGenerator(
#     rescale=1./255,
#     validation_split=0.2
# )

# train_data = datagen.flow_from_directory(
#     DATASET_PATH,
#     target_size=(IMG_SIZE, IMG_SIZE),
#     batch_size=BATCH_SIZE,
#     class_mode='categorical',
#     subset='training'
# )

# val_data = datagen.flow_from_directory(
#     DATASET_PATH,
#     target_size=(IMG_SIZE, IMG_SIZE),
#     batch_size=BATCH_SIZE,
#     class_mode='categorical',
#     subset='validation'
# )

# """Output classes should be:

# No_Fibrosis
# Fibrosis
# Cirrhosis

# Transfer Learning (ImageNet)
# This loads DenseNet pretrained on ImageNet.
# """

# base_model = DenseNet121(
#     weights='imagenet',
#     include_top=False,
#     input_shape=(224,224,3)
# )

# """Freeze base layers:"""

# for layer in base_model.layers:
#     layer.trainable = False

# """Add Custom Classification Layers, Softmax/DenseNet output probabilities

# """

# x = base_model.output
# x = GlobalAveragePooling2D()(x)
# x = Dense(256, activation='relu')(x)
# x = Dropout(0.5)(x)

# predictions = Dense(3, activation='softmax')(x)

# model = Model(inputs=base_model.input, outputs=predictions)

# """Compile Model"""

# model.compile(
#     optimizer=Adam(learning_rate=0.0001),
#     loss='categorical_crossentropy',
#     metrics=['accuracy']
# )

# """Train Model"""

# history = model.fit(
#     train_data,
#     validation_data=val_data,
#     epochs=10
# )

# """Fine‑Tuning
# Unfreeze top DenseNet layers.


# """

# for layer in base_model.layers[-50:]:
#     layer.trainable = True

# """Recompile:"""

# model.compile(
#     optimizer=Adam(learning_rate=1e-5),
#     loss='categorical_crossentropy',
#     metrics=['accuracy']
# )

# """Train again:"""

# history_fine = model.fit(
#     train_data,
#     validation_data=val_data,
#     epochs=5
# )

# """Save the Model"""

# model.save("liver_ultrasound_densenet.h5")

# """Download it:"""

# from google.colab import files
# files.download("liver_ultrasound_densenet.h5")